spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/dbtechthor?options=-c%20search_path=employee_directory
    username: techthor
    password: changeme
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    rest:
      base-path: /api
      default-page-size: 20

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:scott}
      password: ${SPRING_SECURITY_USER_PASSWORD:tiger}

springdoc:
  swagger-ui:
    path: /docs

# Optional: override OpenAPI JSON docs path
# springdoc:
#   api-docs:
#     path: /v3/api-docs
