DROP TABLE IF EXISTS taco_ingredients;
DROP TABLE IF EXISTS taco;
DROP TABLE IF EXISTS ingredient;
DROP TABLE IF EXISTS taco_order;

CREATE TABLE ingredient (
    id VARCHAR(10) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(10) NOT NULL
);

CREATE TABLE taco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE taco_ingredients (
    taco_id BIGINT NOT NULL,
    ingredient_id VARCHAR(10) NOT NULL,
    FOREIGN KEY (taco_id) REFERENCES taco(id),
    FOREIGN KEY (ingredient_id) REFERENCES ingredient(id)
);

CREATE TABLE taco_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_name VARCHAR(50) NOT NULL,
    delivery_street VARCHAR(50) NOT NULL,
    delivery_city VARCHAR(50) NOT NULL,
    delivery_state VARCHAR(10) NOT NULL,
    delivery_zip VARCHAR(10) NOT NULL,
    cc_number VARCHAR(20) NOT NULL,
    cc_expiration VARCHAR(5) NOT NULL,
    cc_cvv VARCHAR(4) NOT NULL
);

-- Optional: Mapping Taco -> TacoOrder (if needed manually)
ALTER TABLE taco ADD COLUMN order_id BIGINT;
ALTER TABLE taco
  ADD CONSTRAINT fk_order
  FOREIGN KEY (order_id) REFERENCES taco_order(id);
