version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - /home/thor/development/JavaProgramming/fromJava2SpringBoot/SpringBootAngularFullstack/backend/.env
    volumes:
    - /home/thor/development/JavaProgramming/fromJava2SpringBoot/SpringBootAngularFullstack/wallet:/app/wallet
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        API_BASE_URL: http://backend:8080/api
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    driver: bridge
