-- Benutzer anlegen
CREATE USER ec IDENTIFIED BY ec
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

-- Rechte vergeben
GRANT CONNECT, RESOURCE TO ec;
ALTER USER ec ACCOUNT UNLOCK;