CREATE TABLE product_category (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(255)
);

CREATE TABLE product (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR2(255),
    name VARCHAR2(255),
    description VARCHAR2(255),
    unit_price NUMBER(13,2),
    image_url VARCHAR2(255),
    active NUMBER(1) DEFAULT 1,
    units_in_stock NUMBER(11),
    date_created TIMESTAMP,
    last_updated TIMESTAMP,
    category_id NUMBER NOT NULL,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES product_category(id)
);

CREATE TABLE customer (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(255),
    last_name VARCHAR2(255),
    email VARCHAR2(255)
);

CREATE TABLE address (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street VARCHAR2(255),
    city VARCHAR2(255),
    state VARCHAR2(255),
    country VARCHAR2(255),
    zip_code VARCHAR2(255)
);

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_tracking_number VARCHAR2(255),
    total_price NUMBER(19,2),
    total_quantity NUMBER,
    status VARCHAR2(128),
    date_created TIMESTAMP,
    last_updated TIMESTAMP,
    customer_id NUMBER,
    billing_address_id NUMBER,
    shipping_address_id NUMBER,
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customer(id),
    CONSTRAINT fk_billing_address FOREIGN KEY (billing_address_id) REFERENCES address(id),
    CONSTRAINT fk_shipping_address FOREIGN KEY (shipping_address_id) REFERENCES address(id)
);

CREATE TABLE order_item (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR2(255),
    quantity NUMBER,
    unit_price NUMBER(19,2),
    order_id NUMBER,
    product_id NUMBER,
    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE country (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(2),
    name VARCHAR2(255)
);

CREATE TABLE state (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    country_id NUMBER,
    CONSTRAINT fk_state_country FOREIGN KEY (country_id) REFERENCES country(id)
);
